## -*- Mode: makefile -*-
## REPLACE WITH YOUR XULRNNER SDK DIRECTORY
LIBXUL_SDK = /usr/lib/xulrunner-devel-2.0

## REPLACE WITH YOUR NSPR CFLAGS
NSPR_INCLUDES = -I/usr/include/nspr
## REPLACE WITH YOUR NSPR LIBS
NSPR_LIBS = -lplds4 -lplc4 -lnspr4 -lpthread -ldl

## REPLACE WITH YOUR CHMLIB CFLAGS
CHMLIB_INCLUDES = -I/usr/include
## REPLACE WITH YOUR CHMLIB LIBS
CHMLIB_LIBS = -lchm

include ./common.mk
