LIBXUL_SDK = /usr/lib/xulrunner-devel-5.0

NSPR_INCLUDES = -I/usr/include/nspr
NSPR_LIBS = -lplds4 -lplc4 -lnspr4 -lpthread -ldl

CHMLIB_INCLUDES = -I/usr/include
CHMLIB_LIBS = -lchm

include ./common.mk
